/**
 * Generates src/generated/version.ts from package.json at build time.
 * This avoids runtime Node.js dependencies (fs, path) so the SDK works in browsers.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf-8'));

const outDir = resolve(root, 'src', 'generated');
mkdirSync(outDir, { recursive: true });

writeFileSync(
  resolve(outDir, 'version.ts'),
  `// Auto-generated by scripts/generate-version.js — do not edit manually.\nexport const VERSION = ${JSON.stringify(version)};\n`,
);
